[color]
horizontal_gradient = 1
horizontal_gradient_color_1 = '{{colors.outline.default.hex}}'
horizontal_gradient_color_2 = '{{colors.tertiary_container.default.hex}}'
horizontal_gradient_color_3 = '{{colors.primary.default.hex}}'
horizontal_gradient_color_4 = '{{colors.secondary.default.hex}}'
horizontal_gradient_color_5 = '{{colors.tertiary.default.hex}}'
horizontal_gradient_color_6 = '{{colors.primary.default.hex}}'
horizontal_gradient_color_7 = '{{colors.tertiary.default.hex}}'
horizontal_gradient_color_8 = '{{colors.on_surface_variant.default.hex}}'