# https://wiki.hypr.land/Configuring/Variables/#input

# My prefered keyboard is English US (intl)
# Layouts and variants can be listed with localectl list-x11-keymap-<layouts/variants>

input {
    kb_layout = us
    kb_variant = intl

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}

# https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}